version: '3.8'

services:
  frontend:
    build: ./frontend
    image: my-frontend-app
    ports:
      - "5173:5173"
    depends_on:
      - server
      - compiler

  server:
    build: ./server
    image: my-backend-server
    ports:
      - "3000:3000"

  compiler:
    build: ./compiler
    image: my-compiler-service
    ports:
      - "3001:3001"
